# Generated by Django 5.1 on 2024-08-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='library',
        ),
        migrations.RemoveField(
            model_name='library',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='relationship_app.author'),
        ),
        migrations.AddField(
            model_name='library',
            name='librarian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationship_app.librarian'),
        ),
    ]
